# Python Basics for Deep Learning

In this notebook, we will cover the basics of Python programming and introduce NumPy, a powerful library for numerical computations. These foundational skills are essential for understanding and implementing deep learning models.

## Python Basics

Let's start with some basic Python concepts.

In [ ]:
# Integer
a = 5
print(f"a: {a}, type: {type(a)}")  # f-strings provide a way to embed expressions inside string literals

# Float
b = 3.2
print(f"b: {b}, type: {type(b)}")

# String
c = "Hello"
print(f"c: {c}, type: {type(c)}")

# Boolean
d = True
print(f"d: {d}, type: {type(d)}")

# List
e = [1, 2, 3]
print(f"e: {e}, type: {type(e)}")

# Dictionary
f = {'name': 'Alice', 'age': 25}
print(f"f: {f}, type: {type(f)}")

a: 5, type: <class 'int'>
b: 3.2, type: <class 'float'>
c: Hello, type: <class 'str'>
d: True, type: <class 'bool'>
e: [1, 2, 3], type: <class 'list'>
f: {'name': 'Alice', 'age': 25}, type: <class 'dict'>


In [ ]:
# If-Else
x = 10
if x > 5:
    print("x is greater than 5")
else:
    print("x is not greater than 5")

x is greater than 5


In [ ]:
# For Loop
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
# While Loop
count = 0
while count < 5:
    print(count)
    count += 1

0
1
2
3
4


### Exercise

Create a list of numbers from 1 to 10 and print the square of each number using a for loop.

In [ ]:
# Create a list of numbers from 1 to 10
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Loop through each number and print its square
for number in numbers:
    square = number ** 2
    print(f"The square of {number} is {square}")

The square of 1 is 1
The square of 2 is 4
The square of 3 is 9
The square of 4 is 16
The square of 5 is 25
The square of 6 is 36
The square of 7 is 49
The square of 8 is 64
The square of 9 is 81
The square of 10 is 100


In [ ]:
# Function Definition
def add(a, b):
    return a + b

# Function Call
result = add(3, 5)
print(f"Result of addition: {result}")

Result of addition: 8


In [ ]:
# Recursive Function (Factorial)
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

# Factorial of 5
print(f"Factorial of 5: {factorial(5)}")

Factorial of 5: 120


### Exercise

Write a Python function to find the factorial of a number using a loop.

In [ ]:
def factorial(n):
    result = 1
    for i in range(1, n + 1):
        result = result * i
    return result

# Test the function
number = 5
print(f"The factorial of {number} is {factorial(number)}")

The factorial of 5 is 120


## Introduction to NumPy

NumPy is a powerful library for numerical computations. It provides support for arrays, matrices, and many mathematical functions.

In [ ]:
import numpy as np

# Creating Arrays
arr = np.array([1, 2, 3, 4])
print(f"Array: {arr}, type: {type(arr)}")

# Array of zeros
zeros = np.zeros(3)
print(f"Array of zeros:\n{zeros}")

# Array of ones
ones = np.ones(2)
print(f"Array of ones:\n{ones}")

# Random Array
random_arr = np.random.random(3)
print(f"Random array:\n{random_arr}")

Array: [1 2 3 4], type: <class 'numpy.ndarray'>
Array of zeros:
[0. 0. 0.]
Array of ones:
[1. 1.]
Random array:
[0.93792832 0.19027025 0.96861356]


In [ ]:
# Element-wise addition
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_arr = arr1 + arr2
print(f"Element-wise addition: {sum_arr}")

Element-wise addition: [5 7 9]


In [ ]:
# Element-wise multiplication
mul_arr = arr1 * arr2
print(f"Element-wise multiplication: {mul_arr}")

Element-wise multiplication: [ 4 10 18]


In [ ]:
# Dot Product
dot_product = np.dot(arr1, arr2)
print(f"Dot product: {dot_product}")

Dot product: 32


### Exercise

Write a custom function to calculate the dot product of two arrays.

In [ ]:
def dot_product(arr1, arr2):
    if len(arr1) != len(arr2):
        raise ValueError("Arrays must have the same length.")

    dot_product_result = 0
    for a, b in zip(arr1, arr2):    # zip(arr1, arr2) pairs up elements from arr1 and arr2
        dot_product_result += a * b

    return dot_product_result

# Test the function
array1 = [1, 2, 3]
array2 = [4, 5, 6]
print(f"The dot product of {array1} and {array2} is {dot_product(array1, array2)}")

The dot product of [1, 2, 3] and [4, 5, 6] is 32


In [ ]:
# Create a matrix
matrix_a = np.array([[1, 2], [3, 4]])
print("Matrix A:\n", matrix_a)

Matrix A:
 [[1 2]
 [3 4]]


In [ ]:
# Matrix transpose
matrix_a_transpose = np.transpose(matrix_a)
print("Transpose of Matrix A:\n", matrix_a_transpose)

Transpose of Matrix A:
 [[1 3]
 [2 4]]


In [ ]:
# Matrix multiplication
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)
print("Dot product of Matrix A and B:\n", matrix_product)

Dot product of Matrix A and B:
 [[19 22]
 [43 50]]


In [ ]:
# Element-wise multiplication
elementwise_product = matrix_a * matrix_b
print("Element-wise multiplication of Matrix A and B:\n", elementwise_product)

Element-wise multiplication of Matrix A and B:
 [[ 5 12]
 [21 32]]


In [ ]:
# Determinant of a matrix
determinant_a = np.linalg.det(matrix_a)
print("Determinant of Matrix A:", determinant_a)

Determinant of Matrix A: -2.0000000000000004


In [ ]:
# Inverse of a matrix
if determinant_a != 0:
    inverse_a = np.linalg.inv(matrix_a)
    print("Inverse of Matrix A:\n", inverse_a)
else:
    print("Matrix A is singular and does not have an inverse.")

Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Exercise

Verify the associative property of matrix multiplication.

In [ ]:
# Verifying Associative Law: (A*B)*C = A*(B*C)
matrix_c = np.array([[2, 0], [1, 2]])
left_associative = np.dot(np.dot(matrix_a, matrix_b), matrix_c)
right_associative = np.dot(matrix_a, np.dot(matrix_b, matrix_c))
print("Associative Law:", np.array_equal(left_associative, right_associative))

Associative Law: True
